### PR TITLE
[ECO-4845] Fix wildcard clientId 

### LINKED ISSUE #414: Failing Test - retrieves two pages of messages before channel was attached
One of the test started failing on main due to recent changes deployed on sandbox
[retrieves two pages of messages before channel was attached](https://github.com/ably/ably-ruby/blob/062d98f98d4c67a7423ad7a4bb5856b3621e4f71/spec/acceptance/realtime/channel_history_spec.rb#L212)
with error
`
2024-06-20 17:53:45.015 ERROR [BSoVdP1hrw] An exception in an external block was caught. Ably::Exceptions::InvalidRequest: invalid clientId; requested clientId cannot be wildcard (status: 400, code: 40012) (code: 40012, http status: 400) -> see https://help.ably.io/error/40012 for help
`

Link to internal discussion - https://ably-real-time.slack.com/archives/C8SPU4589/p1718885475429199

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4845) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by sacOO7**
Fixed #414 
1. Added client_id_for_request method
2. Added method client_id_for_request_sync to realtime auth
3. Annotated implementation with right spec

### CODE REVIEW

File: lib/ably/auth.rb [hunk 1]
```diff
@@ -411,11 +411,15 @@ def auth_header
...
-    #
+    # spec - RSA7e
     # @return [Hash] headers
-    def extra_auth_headers
-      if client_id && using_basic_auth?
-        { 'X-Ably-ClientId' => Base64.urlsafe_encode64(client_id) }
+    def client_id_header(realtime=false)
+      if options[:client_id] && using_basic_auth?
+        if realtime
+          { 'clientId' => options[:client_id] }
```
Comment (AndyTWF) [inline lib/ably/auth.rb:419]: For realtime connections the `clientId` is passed in the query params, not as a header - see RSA7e1

Comment (AndyTWF) [reply lib/ably/auth.rb:419]: I think by putting the realtime setting in a method that explicitly mentions header (even if its later put in the right place by subsequent code) is going to make things confusing

Comment (sacOO7) [reply lib/ably/auth.rb:419]: Yeah, it's just a naming convention. I will try to make it more meaningful 👍

Comment (sacOO7) [reply lib/ably/auth.rb:419]: Updated -> https://github.com/ably/ably-ruby/pull/418/commits/bb4b71f0abe7e17d58d1d10562fb7fd70a66f351

Comment (AndyTWF) [reply lib/ably/auth.rb:419]: This doesn't alleviate my concern - I think we shouldn't be using the word `header` in the method name because sometimes it won't be a header.

Perhaps something like `request_client_id` or similar.

Comment (sacOO7) [reply lib/ably/auth.rb:419]: wdyt think about `include_cliend_id`

Comment (sacOO7) [reply lib/ably/auth.rb:419]: maybe `custom_client_id` or `external_client_id`

Comment (sacOO7) [reply lib/ably/auth.rb:419]: updated -> https://github.com/ably/ably-ruby/pull/418/commits/0f49edecd66af3e27b7fc5efb75c871e0dccf647

**Comment by lawrence-forooghian** [comment]
@sacOO7 is this a bug that only affects the v2 branch? If not, then shouldn't the fix go into `main` so that we can release it ASAP?

**Comment by sacOO7** [comment]
> @sacOO7 is this a bug that only affects the v2 branch? If not, then shouldn't the fix go into `main` so that we can release it ASAP?
Actually, this bug was caused by server side changes, so they have patched a fix that will work for ably-ruby <= 1.2.5
Link to internal conversation for more information -> https://ably-real-time.slack.com/archives/C8SPU4589/p1718885475429199

File: lib/ably/auth.rb [hunk 2]
```diff
@@ -482,15 +486,16 @@ def can_assume_client_id?(assumed_client_id)
...
-      # If new client ID from Ably is a wildcard, but preconfigured clientId is set, then keep the existing clientId
-      if has_client_id? && new_client_id == '*'
-        @client_id_validated = true
-        return
-      end
-
-      # If client_id is defined and not a wildcard, prevent it changing, this is not supported
-      if client_id && client_id != '*' &&  new_client_id != client_id
-        raise Ably::Exceptions::IncompatibleClientId.new("Client ID is immutable once configured for a client. Client ID cannot be changed to '#{new_client_id}'")
+      if has_client_id?
```
Comment (lawrence-forooghian) [inline lib/ably/auth.rb:489]: What is the purpose of this change? Doesn't seem related to the rest of the commit.

File: lib/ably/realtime/connection.rb [hunk 3]
```diff
@@ -470,7 +470,7 @@ def create_websocket_transport
                 'false'
               end
 
-              url_params['clientId'] = client.auth.client_id if client.auth.has_client_id?
+              url_params.merge!(client.auth.client_id_header_sync) # RSA7e1
```
Comment (lawrence-forooghian) [inline lib/ably/realtime/connection.rb]: The commit message describes this as a "refactor" but it's not, right? It's a behaviour change (bug fix).

File: lib/ably/realtime/presence/members_map.rb [hunk 4]
```diff
@@ -228,13 +228,11 @@ def setup_event_handlers
 
       def enter_local_members
         local_members.values.each do |member|
-          local_client_id = member.client_id || client.auth.client_id
```
Comment (lawrence-forooghian) [inline lib/ably/realtime/presence/members_map.rb:231]: Why is this commit in this PR? It doesn't seem related. It's already in https://github.com/ably/ably-ruby/pull/410.

File: lib/ably/auth.rb (hunk 2 above)
Comment (sacOO7) [reply lib/ably/auth.rb:489]: Actually, there was a repetitive logic, so it's a small refactoring to better understand conditional checks

File: lib/ably/realtime/presence/members_map.rb (hunk 4 above)
Comment (sacOO7) [reply lib/ably/realtime/presence/members_map.rb:231]: It's not directly related, though we had mentioned to fix it as a part of this PR -> https://github.com/ably/ably-ruby/pull/410#discussion_r1650794411.
I will revert this for the time being to better understand the PR.

Comment (lawrence-forooghian) [reply lib/ably/realtime/presence/members_map.rb:231]: Yeah, it doesn't seem related to the current PR to me.

File: lib/ably/auth.rb (hunk 2 above)
Comment (lawrence-forooghian) [reply lib/ably/auth.rb:489]: OK, I see. It would have been better to put this in a separate commit to avoid confusion.

File: lib/ably/auth.rb (hunk 1 above)
Comment (sacOO7) [reply lib/ably/auth.rb]: Fixed https://github.com/ably/ably-ruby/pull/418/commits/1ff7d6b7877362714542a6fecd70654fa6136941

File: lib/ably/realtime/presence/members_map.rb (hunk 4 above)
Comment (sacOO7) [reply lib/ably/realtime/presence/members_map.rb]: reverted https://github.com/ably/ably-ruby/pull/418/commits/91e5f29b8324196225b113ce81b4fdd441780b67

File: lib/ably/auth.rb (hunk 1 above)
Comment (lawrence-forooghian) [reply lib/ably/auth.rb]: Cool, looks good to me — will leave to @AndyTWF to resolve if happy since it's his thread

**Review by lawrence-forooghian — APPROVED** [review]

File: lib/ably/realtime/connection.rb (hunk 3 above)
Comment (sacOO7) [reply lib/ably/realtime/connection.rb]: latest commit for the change https://github.com/ably/ably-ruby/pull/418/commits/1ff7d6b7877362714542a6fecd70654fa6136941

Comment (lawrence-forooghian) [reply lib/ably/realtime/connection.rb]: I mean, that doesn't really change anything — the original commit is still there and still says "refactor", and this one doesn't clarify it. But I don't particularly want to go back and forth on this so will resolve — please could you be more careful with your usage of the word "refactor" in the future though?

**Review by ttypic — APPROVED** [review]
LGTM!

**Comment by sacOO7** [comment]
Thanks for the review
